--
-- PostgreSQL database dump
--

\restrict 1pzCqqVq0Kz5maeYnKubYbI0Z4KgYjFHWhMB4Q34OAMRVKNZEWkcGbLysXBaFDS

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.products DROP CONSTRAINT IF EXISTS fklag4lc2yiaaehog28yd6lsoao;
ALTER TABLE IF EXISTS ONLY public.vendor_orders DROP CONSTRAINT IF EXISTS fkjlrsoj67iw6pmt6tc619p34ec;
ALTER TABLE IF EXISTS ONLY public.vendor_profiles DROP CONSTRAINT IF EXISTS fkbdoc22aas6cny51wfhae92xit;
ALTER TABLE IF EXISTS ONLY public.warehouses DROP CONSTRAINT IF EXISTS warehouses_pkey;
ALTER TABLE IF EXISTS ONLY public.warehouse_stock DROP CONSTRAINT IF EXISTS warehouse_stock_pkey;
ALTER TABLE IF EXISTS ONLY public.vendor_profiles DROP CONSTRAINT IF EXISTS vendor_profiles_pkey;
ALTER TABLE IF EXISTS ONLY public.vendor_orders DROP CONSTRAINT IF EXISTS vendor_orders_pkey;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.coupons DROP CONSTRAINT IF EXISTS ukeplt0kkm9yf2of2lnx6c1oy9b;
ALTER TABLE IF EXISTS ONLY public.warehouses DROP CONSTRAINT IF EXISTS uk6herdbg4x5wp6gkor8epv73oc;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS uk6dotkott2kjsp8vw4d0m25fb7;
ALTER TABLE IF EXISTS ONLY public.vendor_profiles DROP CONSTRAINT IF EXISTS uk54wrcif7ltdw3bocsbe3twow9;
ALTER TABLE IF EXISTS ONLY public.warehouses DROP CONSTRAINT IF EXISTS uk2qm0l82n5ivhyqwmgejxxefm1;
ALTER TABLE IF EXISTS ONLY public.products DROP CONSTRAINT IF EXISTS products_pkey;
ALTER TABLE IF EXISTS ONLY public.coupons DROP CONSTRAINT IF EXISTS coupons_pkey;
DROP TABLE IF EXISTS public.warehouses;
DROP TABLE IF EXISTS public.warehouse_stock;
DROP TABLE IF EXISTS public.vendor_profiles;
DROP TABLE IF EXISTS public.vendor_orders;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.products;
DROP TABLE IF EXISTS public.coupons;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: coupons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coupons (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(40) NOT NULL,
    discount_type character varying(20) NOT NULL,
    discount_value double precision NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    maximum_discount double precision,
    minimum_order_amount double precision,
    start_date timestamp(6) without time zone NOT NULL,
    usage_count integer NOT NULL,
    usage_limit integer
);


--
-- Name: coupons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.coupons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    category character varying(255),
    description character varying(255) NOT NULL,
    image_url character varying(255),
    name character varying(255) NOT NULL,
    price double precision NOT NULL,
    vendor_id bigint NOT NULL,
    stock integer DEFAULT 0 NOT NULL,
    sold_quantity integer DEFAULT 0 NOT NULL,
    discount_percentage double precision DEFAULT 0 NOT NULL,
    approval_status character varying(255),
    returned_stock integer DEFAULT 0 NOT NULL
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    role character varying(255),
    password_reset_token character varying(255),
    password_reset_token_expiry timestamp(6) without time zone,
    address character varying(255),
    phone character varying(255),
    commission_percentage double precision DEFAULT 0 NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vendor_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vendor_orders (
    id bigint NOT NULL,
    customer_email character varying(255),
    customer_name character varying(255),
    placed_at timestamp(6) without time zone,
    product_id bigint,
    product_name character varying(255),
    quantity integer NOT NULL,
    status character varying(255),
    total_amount double precision NOT NULL,
    unit_price double precision NOT NULL,
    vendor_id bigint NOT NULL,
    order_status character varying(255),
    customer_phone character varying(255),
    delivery_address character varying(255),
    delivery_method character varying(255),
    order_reference character varying(255),
    payment_method character varying(255),
    customer_notification_read boolean NOT NULL,
    previous_order_status character varying(255),
    refund_details character varying(255),
    refund_processed_at timestamp(6) without time zone,
    refund_reason character varying(255),
    refund_requested_at timestamp(6) without time zone,
    refund_status character varying(255),
    commission_amount double precision DEFAULT 0,
    commission_percentage double precision DEFAULT 0,
    customer_total_amount double precision DEFAULT 0,
    warehouse_name character varying(255),
    warehouse_status character varying(255),
    warehouse_updated_at timestamp(6) without time zone,
    warehouse_allocated_quantity integer DEFAULT 0 NOT NULL
);


--
-- Name: vendor_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vendor_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vendor_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vendor_profiles (
    id bigint NOT NULL,
    address character varying(255),
    business_name character varying(255) NOT NULL,
    contact_number character varying(255),
    description character varying(1000),
    user_id bigint NOT NULL
);


--
-- Name: vendor_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vendor_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.warehouse_stock (
    id bigint NOT NULL,
    available_quantity integer NOT NULL,
    product_id bigint NOT NULL,
    warehouse_id bigint NOT NULL
);


--
-- Name: warehouse_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.warehouse_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.warehouses (
    id bigint NOT NULL,
    active boolean NOT NULL,
    address character varying(255),
    capacity integer NOT NULL,
    code character varying(255) NOT NULL,
    manager character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: warehouses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.warehouses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: coupons; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.coupons (id, active, code, discount_type, discount_value, expiry_date, maximum_discount, minimum_order_amount, start_date, usage_count, usage_limit) FROM stdin;
11	t	ABC	PERCENTAGE	10	2026-09-07 21:09:00	\N	\N	2026-09-06 21:09:00	2	\N
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.products (id, category, description, image_url, name, price, vendor_id, stock, sold_quantity, discount_percentage, approval_status, returned_stock) FROM stdin;
6	Gaming Laptop	High performance gaming laptop with powerful processor, dedicated graphics and premium display	https://example.com/dell-gaming-laptop.jpg	Dell Gaming Laptop Pro	85000	2	8	3	0	\N	0
17	Phone	Fast Android smartphone with a high-refresh display and powerful charging.	https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=900	OnePlus 12	54999	2	12	4	9	\N	0
29	Wearables	Fitness watch with heart-rate tracking, notifications and water resistance.	https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900	Smart Fitness Watch	3999	2	12	3	18	\N	0
14	Laptop	Reliable 15-inch laptop for productivity, study and everyday use.	https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=900	HP Pavilion 15	62999	2	12	1	0	\N	0
24	Accessories	RGB mechanical keyboard with tactile switches and anti-ghosting keys.	https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=900	Mechanical Gaming Keyboard	4499	2	28	2	15	\N	1
9	Laptop	Fast everyday laptop for work, study and entertainment.	https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=900	Lenovo IdeaPad Laptop	54999	2	10	1	8	\N	0
21	earpg	hihhihihfffjffjfjfjfjff		ear phones	120000	2	0	0	50	\N	0
18	Phone	Smartphone with an excellent camera and clean Android experience.	https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=900	Google Pixel 9	74999	2	7	2	6	\N	1
32	aaa	aaaaaa		abc	100000	2	0	1	50	\N	0
25	Accessories	Ergonomic wireless mouse with adjustable DPI and precision tracking.	https://images.unsplash.com/photo-1527814050087-3793815479db?w=900	Wireless Gaming Mouse	2199	2	33	2	10	\N	0
34	Headphones	Premium noise-cancelling headphones with immersive sound and all-day comfort.	https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=900	Sony WH-1000XM5 Headphones	29990	2	12	0	5	\N	0
10	Phone	Modern smartphone with a bright display and powerful camera.	https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=900	Samsung Galaxy Phone	29999	2	20	0	5	\N	0
33	kk	df	\N	cover	100000	2	7	0	10	\N	0
27	Monitor	Slim bezel monitor with vivid colors for work, gaming and entertainment.	https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=900	27-inch Full HD Monitor	15999	2	10	0	8	\N	0
28	Storage	Fast and compact external SSD for backups, media and gaming libraries.	https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=900	Portable SSD 1TB	6999	2	18	0	10	\N	0
23	Laptop	Versatile laptop for study, remote work and everyday multitasking.	https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=900	Acer Aspire 5	57999	2	10	1	7	\N	0
30	Accessories	Plug-and-play webcam for clear video calls, classes and streaming.	https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=900	1080p USB Webcam	2499	2	22	0	14	\N	0
11	Headphones	Comfortable wireless headphones with clear sound and long battery life.	https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=900	Wireless Bluetooth Headphones	2499	2	27	0	20	\N	0
13	Laptop	Lightweight premium laptop with long battery life and fast Apple silicon.	https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=900	Apple MacBook Air M3	99999	2	7	1	10	\N	0
15	Gaming Laptop	High-performance gaming laptop with dedicated graphics and fast display.	https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=900	ASUS ROG Gaming Laptop	114999	2	6	2	15	\N	0
22	Gaming Laptop	Powerful gaming laptop with dedicated graphics, fast refresh rate and upgraded cooling.	https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=900	Dell G15 Gaming Laptop	84999	2	7	2	12	\N	0
16	Phone	Premium smartphone with an advanced camera and smooth performance.	https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=900	Apple iPhone 15	69999	2	9	1	0	\N	0
26	Accessories	Multi-port USB-C hub with HDMI, USB 3.0 and fast charging support.	https://images.unsplash.com/photo-1625842268584-8f3296236761?w=900	USB-C Laptop Hub	1799	2	25	3	12	\N	0
35	Tablet	Powerful Android tablet with a vivid display for work, study and entertainment.	https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=900	Samsung Galaxy Tab S9	55999	2	10	0	8	\N	0
31	Audio	Compact wireless speaker with rich sound and all-day battery life.	https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=900	Bluetooth Portable Speaker	2999	2	3	1	16	\N	0
36	E-reader	Waterproof e-reader with a glare-free display and weeks of battery life.	https://images.unsplash.com/photo-1592496001020-d31bd830651f?w=900	Kindle Paperwhite	13999	2	15	0	0	\N	0
37	Accessories	Ergonomic wireless productivity mouse with quiet clicks and precise tracking.	https://images.unsplash.com/photo-1527814050087-3793815479db?w=900	Logitech MX Master 3S	8999	2	18	0	10	\N	0
38	Audio	Compact true wireless earbuds with rich bass and a portable charging case.	https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=900	JBL Tune Wireless Earbuds	4999	2	24	0	12	\N	0
39	Networking	High-speed dual-band router for reliable whole-home connectivity.	https://images.unsplash.com/photo-1647427060118-4911c9821b82?w=900	TP-Link WiFi 6 Router	6499	2	14	0	0	\N	0
40	Accessories	Fast-charging portable power bank with USB-C and dual USB outputs.	https://images.unsplash.com/photo-1609592424846-7f3d0f4f2d2d?w=900	Anker 20,000mAh Power Bank	3499	2	30	0	7	\N	0
41	car	dfgdfg		fgd	10000000	4	12	0	10	\N	0
42	Audio	Compact wireless earbuds with active noise cancellation and a charging case.	https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=900	Noise Cancelling Earbuds Pro	3499	4	20	0	8	\N	0
43	Home Electronics	Adjustable desk lamp with touch controls, warm light and USB charging.	https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=900	Smart LED Desk Lamp	1899	4	18	0	10	\N	0
44	Accessories	Universal fast charger for phones, tablets and compatible laptops.	https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=900	USB-C Fast Charger 65W	2299	4	30	0	5	\N	0
46	aa	rere		abb	353520	2	12	0	0	\N	0
45	Power	Rechargeable backup power station for travel, work and emergency use.	https://images.unsplash.com/photo-1625842268584-8f3296236761?w=900	Portable Power Station	12999	4	8	0	12	\N	0
48	Headphones	Premium wireless headphones with cushioned ear cups	https://images.unsplash.com/photo-1484704849700-f032a568e944?w=900	Head Set	50000	2	19	1	10	APPROVED	1
49	pen	pen		pen	100	2	0	2	10	APPROVED	1
50	kl	hjg		aka	50000	2	1	1	10	APPROVED	1
51	DFF	ADDDDD		ADDDD	500000	2	5	1	10	APPROVED	1
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, email, password, username, role, password_reset_token, password_reset_token_expiry, address, phone, commission_percentage) FROM stdin;
3	admin@shopstack.com	$2a$10$2vrQX.QbqxeNyDXaG9zH8eH9Ifjnf0ZsSagiLyrRdq4R4vm1GSkvG	Admin	ADMIN	\N	\N	kolkata,Haldia,WB	9798026381	0
2	vendor@shopstack.com	$2a$10$XqZnYgFRvK9qpQMGlWt7jevWiUi6GF8VtKzTnDBTrdhozSJZKn4TO	Shekhar	VENDOR	\N	\N	\N	\N	10
1	himanshu@gmail.com	$2a$10$bJBd5FX4TyZgJKOSx/CfR.KvS5rm4YVi0cwds6DIT4486ZVaH9TJi	Himanshu Shekhar	CUSTOMER	\N	\N	kolkata,WestBengal	9798026381	0
4	vendor2@shopstack.com	$2a$10$wNQw1auV7IvEmhJ9JY8W5.QNkE.1IOjsTUem.jxKz/FOFQ0uxKkvW	sudhanshu	VENDOR	\N	\N	\N	\N	10
5	staff@shopstack.com	$2a$10$KQr9g8GFZCCKMALbkDCyT.FE5YILDZGsSojzrqJ2zhXF1eJA0SgG.	Warehouse Staff	STAFF	\N	\N	\N	\N	10
6	vendor1@shopstack.com	$2a$10$UXnsK4RC/zgtfBsdBYSwL.9XUJUunMZLDnDEUPEbAtS57H.wCIsZC	vendor	VENDOR	\N	\N	\N	\N	10
7	vendor4@shopstack.com	$2a$10$hdTAAHka5f23LP.aMYYjjO92hL35qC88reENFX9Bs10To2UvhyeEO	vendor	VENDOR	\N	\N	\N	\N	10
8	himanshuskh@gmail.com	$2a$10$0rQObV7afqOzBAWMV3ADzeoLOuLPb9mtxbNkyAjsbhduvsIJ.mlRi	skh	CUSTOMER	\N	\N	\N	\N	10
\.


--
-- Data for Name: vendor_orders; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.vendor_orders (id, customer_email, customer_name, placed_at, product_id, product_name, quantity, status, total_amount, unit_price, vendor_id, order_status, customer_phone, delivery_address, delivery_method, order_reference, payment_method, customer_notification_read, previous_order_status, refund_details, refund_processed_at, refund_reason, refund_requested_at, refund_status, commission_amount, commission_percentage, customer_total_amount, warehouse_name, warehouse_status, warehouse_updated_at, warehouse_allocated_quantity) FROM stdin;
14	himanshu@gmail.com	Himanshu Shekhar	2026-08-16 15:48:30.820762	26	USB-C Laptop Hub	1	READ	1583.12	1583.12	2	DELIVERED	9696969696	sdfgs, dgs, dsfg 656565	standard	SS-1786875510807	razorpay	t	DELIVERED		2026-08-30 19:04:32.142253	Wrong product received	2026-08-16 15:58:22.640269	REJECTED	0	0	0	\N	\N	\N	0
17	himanshu@gmail.com	Himanshu Shekhar	2026-08-21 13:14:01.782876	17	OnePlus 12	1	READ	50049.09	50049.09	2	DELIVERED	9798026381	hhhhhh, wb, wb 121212	standard	SS-1787298241760	razorpay	t	DELIVERED		2026-08-30 19:04:35.85679	Product not as described	2026-08-21 13:34:12.083595	REJECTED	5004.909	10	55053.998999999996	\N	AVAILABILITY_CHECK	2026-08-27 19:23:23.137083	0
13	himanshu@gmail.com	Himanshu Shekhar	2026-08-16 15:15:06.698262	24	Mechanical Gaming Keyboard	1	READ	3824.15	3824.15	2	DELIVERED	9696969696	dgsdfg, gsdfg, sgdfg 656565	standard	SS-1786873506677	razorpay	t	\N	\N	\N	\N	\N	\N	0	0	0	\N	\N	\N	0
25	himanshu@gmail.com	Himanshu Shekhar	2026-08-28 15:25:21.401902	14	HP Pavilion 15	1	READ	62999	62999	2	DELIVERED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1787910921349	upi	t	\N	\N	\N	\N	\N	NONE	6299.9	10	62999	Mumbai West	READY_FOR_SHIPMENT	2026-08-28 15:26:02.571798	1
23	himanshu@gmail.com	Himanshu Shekhar	2026-08-27 19:10:37.968111	29	Smart Fitness Watch	1	READ	3279.18	3279.18	2	DELIVERED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1787838037948	razorpay	t	\N	\N	\N	\N	\N	NONE	327.91799999999995	10	3279.18	Mumbai West	READY_FOR_SHIPMENT	2026-08-27 19:29:32.762593	0
5	vendor@shopstack.com	Himanshu Shekhar	2026-08-09 17:27:49.786041	17	OnePlus 12	1	READ	54999	54999	2	DELIVERED	9898989898	afrsfar, ergerg, wergw 656565	standard	SS-1786276669769	razorpay	f	\N	\N	\N	\N	\N	\N	0	0	0	\N	\N	\N	0
8	vendor@shopstack.com	Himanshu Shekhar	2026-08-10 19:01:25.509415	15	ASUS ROG Gaming Laptop	1	READ	97749.15	97749.15	2	DELIVERED	9798026381	gdrgfd, ehraeh, erghaserg 989898	standard	SS-1786368685488	razorpay	f	\N	\N	\N	\N	\N	\N	0	0	0	\N	\N	\N	0
3	vendor@shopstack.com	Himanshu Shekhar	2026-08-09 16:28:38.959929	13	Apple MacBook Air M3	1	READ	99999	99999	2	DELIVERED	9798026381	kolkata,west bengal, Haldia, west bengal 985654	standard	SS-1786273118935	Cash on Delivery	f	\N	\N	\N	\N	\N	\N	0	0	0	\N	\N	\N	0
6	vendor@shopstack.com	Himanshu Shekhar	2026-08-09 17:32:07.989038	6	Dell Gaming Laptop Pro	1	READ	85000	85000	2	DELIVERED	9798026381	kolkata, kolkata, WB 565455	standard	SS-1786276927972	razorpay	f	\N	\N	\N	\N	\N	\N	0	0	0	\N	\N	\N	0
11	vendor@shopstack.com	Himanshu Shekhar	2026-08-15 16:57:33.459392	23	Acer Aspire 5	1	READ	53939.07	53939.07	2	DELIVERED	6545654568	hahgasgsg, sedfga, asdfg 323232	standard	SS-1786793253448	razorpay	f	\N	\N	\N	\N	\N	\N	0	0	0	\N	\N	\N	0
7	vendor@shopstack.com	Himanshu Shekhar	2026-08-09 17:53:18.373101	31	Bluetooth Portable Speaker	1	READ	2519.16	2519.16	2	DELIVERED	9798026381	kolkata, kolkata, WB 123456	standard	SS-1786278198350	razorpay	f	\N	\N	\N	\N	\N	\N	0	0	0	\N	\N	\N	0
4	vendor@shopstack.com	Himanshu Shekhar	2026-08-09 16:34:21.197725	18	Google Pixel 9	1	READ	74999	74999	2	DELIVERED	9798026381	kolkata, kolkata, WB 654123	express	SS-1786273461185	razorpay	f	\N	\N	\N	\N	\N	\N	0	0	0	\N	\N	\N	0
20	himanshu@gmail.com	Himanshu Shekhar	2026-08-23 16:44:48.058066	17	OnePlus 12	1	READ	50049.09	50049.09	2	DELIVERED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1787483688027	upi	t	\N	\N	\N	\N	\N	NONE	5004.909	10	45044.181	Delhi North	READY_FOR_SHIPMENT	2026-08-27 19:08:51.811816	0
19	himanshu@gmail.com	Himanshu Shekhar	2026-08-21 18:03:00.874844	6	Dell Gaming Laptop Pro	1	READ	85000	85000	2	DELIVERED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1787315580854	razorpay	t	\N	\N	\N	\N	\N	NONE	8500	10	85000	\N	AVAILABILITY_CHECK	2026-08-27 19:18:56.147925	0
10	vendor@shopstack.com	Himanshu Shekhar	2026-08-15 16:44:07.972987	32	abc	1	READ	50000	50000	2	DELIVERED	9696969696	hjfdghj, shsfgh, fghsfg 656565	standard	SS-1786792447960	razorpay	f	\N	\N	\N	\N	\N	\N	0	0	0	\N	\N	\N	0
18	himanshu@gmail.com	Himanshu Shekhar	2026-08-21 13:39:56.872203	29	Smart Fitness Watch	1	READ	3279.18	3279.18	2	DELIVERED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1787299796853	razorpay	t	\N	\N	\N	\N	\N	NONE	327.91799999999995	10	3279.18	\N	\N	\N	0
12	admin@shopstack.com	Admin	2026-08-15 18:24:10.677357	6	Dell Gaming Laptop Pro	1	READ	85000	85000	2	DELIVERED	6564636363	gfhdfhg, fghd, gfhd 636363	standard	SS-1786798450662	razorpay	t	\N	\N	\N	\N	\N	\N	0	0	0	\N	\N	\N	0
9	admin@shopstack.com	Admin	2026-08-15 16:22:18.779851	15	ASUS ROG Gaming Laptop	1	READ	97749.15	97749.15	2	DELIVERED	9696969696	kolkata, haldia, wb 654654	standard	SS-1786791138758	razorpay	t	\N	\N	\N	\N	\N	\N	0	0	0	\N	\N	\N	0
21	himanshu@gmail.com	Himanshu Shekhar	2026-08-24 17:33:34.78485	22	Dell G15 Gaming Laptop	1	READ	74799.12	74799.12	2	DELIVERED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1787573014722	upi	t	\N	\N	\N	\N	\N	NONE	7479.911999999999	10	67319.208	Delhi North	READY_FOR_SHIPMENT	2026-08-27 19:07:34.045805	0
24	himanshu@gmail.com	Himanshu Shekhar	2026-08-27 19:47:18.318806	26	USB-C Laptop Hub	1	READ	1583.12	1583.12	2	DELIVERED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1787840238297	razorpay	t	\N	\N	\N	\N	\N	NONE	158.31199999999998	10	1583.12	Mumbai West	READY_FOR_SHIPMENT	2026-08-27 20:03:31.967133	0
22	himanshu@gmail.com	Himanshu Shekhar	2026-08-27 18:53:01.356391	29	Smart Fitness Watch	1	READ	3279.18	3279.18	2	DELIVERED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1787836981337	razorpay	t	\N	\N	\N	\N	\N	NONE	327.91799999999995	10	3279.18	Bengaluru Central	READY_FOR_SHIPMENT	2026-08-27 19:01:08.566957	0
26	himanshu@gmail.com	Himanshu Shekhar	2026-08-28 16:11:14.585441	9	Lenovo IdeaPad Laptop	1	READ	50599.08	50599.08	2	DELIVERED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1787913674570	razorpay	t	\N	\N	\N	\N	\N	NONE	5059.908	10	50599.08	Bengaluru Central	READY_FOR_SHIPMENT	2026-08-28 16:17:38.59743	1
30	himanshu@gmail.com	Himanshu Shekhar	2026-08-30 18:35:00.703622	48	Head Set	1	READ	45000	45000	2	REFUNDED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1788095100683	razorpay	t	DELIVERED	defective	2026-08-30 19:22:44.640671	Defective or damaged product	2026-08-30 19:01:09.768324	REFUNDED	4050	10	40500	Delhi North	DELIVERED	2026-08-30 18:43:25.518392	1
16	himanshu@gmail.com	Himanshu Shekhar	2026-08-20 14:23:03.759837	16	Apple iPhone 15	1	READ	69999	69999	2	DELIVERED	9798026381	kolkata, haldia, WB 879856	express	SS-1787215983717	razorpay	t	DELIVERED		2026-08-30 19:04:34.529671	Product not as described	2026-08-20 14:37:00.31939	REJECTED	0	0	0	\N	\N	\N	0
15	himanshu@gmail.com	Himanshu Shekhar	2026-08-16 16:26:06.557529	15	ASUS ROG Gaming Laptop	1	READ	97749.15	97749.15	2	DELIVERED	9898989898	redgwe, gwerg, ergw 969696	standard	SS-1786877766540	razorpay	t	DELIVERED	oijk	2026-08-30 19:04:32.968103	Defective or damaged product	2026-08-16 16:28:16.711392	REJECTED	0	0	0	\N	\N	\N	0
33	himanshu@gmail.com	Himanshu Shekhar	2026-08-30 20:44:56.004967	24	Mechanical Gaming Keyboard	1	READ	3824.15	3824.15	2	REFUNDED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1788102895976	razorpay	t	DELIVERED	damaged\n	2026-08-30 20:59:38.971086	Defective or damaged product	2026-08-30 20:58:49.589681	REFUNDED	344.1735	10	3441.735	Bengaluru Central	DELIVERED	2026-08-30 20:57:00.785505	1
32	himanshu@gmail.com	Himanshu Shekhar	2026-08-30 19:59:03.704259	49	pen	1	READ	90	90	2	RETURN_DELIVERED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1788100143683	razorpay	t	DELIVERED	damaged\n	2026-08-30 20:01:35.696487	Defective or damaged product	2026-08-30 20:01:27.712841	RETURN_DELIVERED	8.1	10	81	Mumbai West	DELIVERED	2026-08-30 20:00:59.422938	1
34	himanshu@gmail.com	Himanshu Shekhar	2026-08-31 17:33:46.483978	18	Google Pixel 9	1	READ	70499.06	70499.06	2	REFUNDED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1788177826463	upi	t	DELIVERED		2026-09-03 15:50:06.608056	Defective or damaged product	2026-08-31 17:50:34.294629	REFUNDED	7049.906	10	70499.06	Bengaluru Central	DELIVERED	2026-08-31 17:50:12.643313	1
29	himanshu@gmail.com	Himanshu Shekhar	2026-08-30 16:55:44.079294	25	Wireless Gaming Mouse	1	READ	1979.1	1979.1	2	DELIVERED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1788089144056	razorpay	t	\N	\N	\N	\N	\N	NONE	197.91	10	1979.1	Bengaluru Central	READY_FOR_SHIPMENT	2026-08-30 17:27:02.587773	1
27	himanshu@gmail.com	Himanshu Shekhar	2026-08-28 16:19:55.082265	26	USB-C Laptop Hub	1	READ	1583.12	1583.12	2	DELIVERED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1787914195073	upi	t	\N	\N	\N	\N	\N	NONE	158.31199999999998	10	1583.12	Bengaluru Central	READY_FOR_SHIPMENT	2026-08-28 16:20:45.091488	1
28	himanshu@gmail.com	Himanshu Shekhar	2026-08-29 16:23:00.049455	22	Dell G15 Gaming Laptop	1	READ	74799.12	74799.12	2	DELIVERED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1788000780019	razorpay	t	\N	\N	\N	\N	\N	NONE	6731.9208	10	67319.208	Delhi North	READY_FOR_SHIPMENT	2026-08-29 16:25:31.362281	1
31	himanshu@gmail.com	Himanshu Shekhar	2026-08-30 19:46:49.235675	49	pen	1	READ	90	90	2	REFUNDED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1788099409201	razorpay	t	DELIVERED	wrong product\n	2026-08-30 19:53:39.88918	Product not as described	2026-08-30 19:52:33.81543	REFUNDED	8.1	10	81	Bengaluru Central	DELIVERED	2026-08-30 19:51:30.820905	1
36	himanshu@gmail.com	Himanshu Shekhar	2026-08-31 18:55:24.113096	51	ADDDD	1	READ	450000	450000	2	REFUNDED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1788182724088	upi	t	DELIVERED		2026-08-31 18:57:56.061397	Defective or damaged product	2026-08-31 18:56:55.063496	REFUNDED	40500	10	405000	Bengaluru Central	DELIVERED	2026-08-31 18:56:23.837305	1
35	himanshu@gmail.com	Himanshu Shekhar	2026-08-31 17:38:56.322504	50	aka	1	READ	45000	45000	2	REFUNDED	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1788178136307	razorpay	t	DELIVERED	defect	2026-08-31 17:46:15.774657	Defective or damaged product	2026-08-31 17:43:56.040437	REFUNDED	4500	10	45000	Bengaluru Central	DELIVERED	2026-08-31 17:43:15.877719	1
38	himanshu@gmail.com	Himanshu Shekhar	2026-09-06 21:35:14.802475	25	Wireless Gaming Mouse	1	READ	1979.1	1979.1	2	PROCESSING	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1788710714787	razorpay	t	\N	\N	\N	\N	\N	NONE	178.11899999999997	10	1781.1899999999998	\N	ORDER_CONFIRMED	\N	0
37	himanshu@gmail.com	Himanshu Shekhar	2026-09-06 21:25:00.844387	17	OnePlus 12	1	READ	50049.09	50049.09	2	PROCESSING	9798026381	kolkata,WestBengal, Haldia, West Bengal 233445	standard	SS-1788710100797	razorpay	t	\N	\N	\N	\N	\N	NONE	4504.418099999999	10	45044.181	\N	ORDER_CONFIRMED	\N	0
\.


--
-- Data for Name: vendor_profiles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.vendor_profiles (id, address, business_name, contact_number, description, user_id) FROM stdin;
1	New Kolkata	TechStore Premium Electronics	9798026381	Premium laptop and smartphone seller	2
3	KOLKATA	GROCERY SHOP	9798026381		4
\.


--
-- Data for Name: warehouse_stock; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.warehouse_stock (id, available_quantity, product_id, warehouse_id) FROM stdin;
1	3	22	1
3	2	22	2
4	4	29	1
5	4	29	3
8	9	26	3
10	7	10	1
11	7	10	3
12	6	10	2
13	5	17	1
14	4	17	3
15	4	17	2
16	3	6	1
17	3	6	3
18	3	6	2
19	0	21	1
20	0	21	3
21	0	21	2
22	5	14	1
23	5	14	3
25	0	32	1
26	0	32	3
27	0	32	2
29	3	18	3
30	2	18	2
31	9	11	1
32	9	11	3
33	9	11	2
35	12	25	3
36	11	25	2
37	3	33	1
38	2	33	3
39	2	33	2
40	4	27	1
41	3	27	3
42	3	27	2
43	6	28	1
44	6	28	3
45	6	28	2
46	4	23	1
47	3	23	3
48	3	23	2
49	8	30	1
50	7	30	3
51	7	30	2
53	4	9	3
54	4	9	2
55	3	13	1
56	2	13	3
57	2	13	2
58	2	15	1
59	2	15	3
60	2	15	2
61	3	16	1
62	3	16	3
63	3	16	2
64	4	34	1
65	4	34	3
66	4	34	2
68	10	24	3
69	9	24	2
70	4	35	1
71	3	35	3
72	3	35	2
73	1	31	1
74	1	31	3
75	1	31	2
76	5	36	1
77	5	36	3
78	5	36	2
79	6	37	1
80	6	37	3
81	6	37	2
82	8	38	1
83	8	38	3
84	8	38	2
85	5	39	1
86	5	39	3
87	4	39	2
88	10	40	1
89	10	40	3
90	10	40	2
91	4	41	1
92	4	41	3
93	4	41	2
94	7	42	1
95	7	42	3
96	6	42	2
97	6	43	1
98	6	43	3
99	6	43	2
100	10	44	1
101	10	44	3
102	10	44	2
103	3	45	1
104	3	45	3
105	2	45	2
6	3	29	2
9	8	26	2
24	3	14	2
52	3	9	1
7	8	26	1
106	4	46	1
107	4	46	3
108	4	46	2
109	5	47	1
110	3	47	2
111	4	47	3
2	2	22	3
34	11	25	1
112	10	48	1
113	5	48	2
114	4	48	3
115	0	49	1
116	0	49	2
67	9	24	1
118	1	50	2
117	0	50	1
28	2	18	1
120	2	51	2
121	2	51	3
119	1	51	1
\.


--
-- Data for Name: warehouses; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.warehouses (id, active, address, capacity, code, manager, name) FROM stdin;
1	t	Peenya Industrial Area, Bengaluru	1200	BLR-01	Warehouse team	Bengaluru Central
2	t	Andheri East, Mumbai	1500	MUM-01	Warehouse team	Mumbai West
3	t	Bawana Industrial Area, Delhi	1000	DEL-01	Warehouse team	Delhi North
\.


--
-- Name: coupons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.coupons_id_seq', 11, true);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.products_id_seq', 51, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 8, true);


--
-- Name: vendor_orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.vendor_orders_id_seq', 38, true);


--
-- Name: vendor_profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.vendor_profiles_id_seq', 3, true);


--
-- Name: warehouse_stock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.warehouse_stock_id_seq', 121, true);


--
-- Name: warehouses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.warehouses_id_seq', 3, true);


--
-- Name: coupons coupons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: warehouses uk2qm0l82n5ivhyqwmgejxxefm1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warehouses
    ADD CONSTRAINT uk2qm0l82n5ivhyqwmgejxxefm1 UNIQUE (name);


--
-- Name: vendor_profiles uk54wrcif7ltdw3bocsbe3twow9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendor_profiles
    ADD CONSTRAINT uk54wrcif7ltdw3bocsbe3twow9 UNIQUE (user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: warehouses uk6herdbg4x5wp6gkor8epv73oc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warehouses
    ADD CONSTRAINT uk6herdbg4x5wp6gkor8epv73oc UNIQUE (code);


--
-- Name: coupons ukeplt0kkm9yf2of2lnx6c1oy9b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT ukeplt0kkm9yf2of2lnx6c1oy9b UNIQUE (code);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vendor_orders vendor_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendor_orders
    ADD CONSTRAINT vendor_orders_pkey PRIMARY KEY (id);


--
-- Name: vendor_profiles vendor_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendor_profiles
    ADD CONSTRAINT vendor_profiles_pkey PRIMARY KEY (id);


--
-- Name: warehouse_stock warehouse_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warehouse_stock
    ADD CONSTRAINT warehouse_stock_pkey PRIMARY KEY (id);


--
-- Name: warehouses warehouses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warehouses
    ADD CONSTRAINT warehouses_pkey PRIMARY KEY (id);


--
-- Name: vendor_profiles fkbdoc22aas6cny51wfhae92xit; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendor_profiles
    ADD CONSTRAINT fkbdoc22aas6cny51wfhae92xit FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: vendor_orders fkjlrsoj67iw6pmt6tc619p34ec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendor_orders
    ADD CONSTRAINT fkjlrsoj67iw6pmt6tc619p34ec FOREIGN KEY (vendor_id) REFERENCES public.users(id);


--
-- Name: products fklag4lc2yiaaehog28yd6lsoao; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fklag4lc2yiaaehog28yd6lsoao FOREIGN KEY (vendor_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 1pzCqqVq0Kz5maeYnKubYbI0Z4KgYjFHWhMB4Q34OAMRVKNZEWkcGbLysXBaFDS

