--
-- PostgreSQL database dump
--

\restrict aZlBYzDhi08cj7wQs8ZRrf6ALRJ6ee5o7fLKtER4i2x3BV3xakTdQQ8mB1SkupB

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.products DROP CONSTRAINT IF EXISTS fklag4lc2yiaaehog28yd6lsoao;
ALTER TABLE IF EXISTS ONLY public.vendor_orders DROP CONSTRAINT IF EXISTS fkjlrsoj67iw6pmt6tc619p34ec;
ALTER TABLE IF EXISTS ONLY public.vendor_profiles DROP CONSTRAINT IF EXISTS fkbdoc22aas6cny51wfhae92xit;
ALTER TABLE IF EXISTS ONLY public.warehouses DROP CONSTRAINT IF EXISTS warehouses_pkey;
ALTER TABLE IF EXISTS ONLY public.warehouse_stock DROP CONSTRAINT IF EXISTS warehouse_stock_pkey;
ALTER TABLE IF EXISTS ONLY public.vendor_profiles DROP CONSTRAINT IF EXISTS vendor_profiles_pkey;
ALTER TABLE IF EXISTS ONLY public.vendor_orders DROP CONSTRAINT IF EXISTS vendor_orders_pkey;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.coupons DROP CONSTRAINT IF EXISTS ukeplt0kkm9yf2of2lnx6c1oy9b;
ALTER TABLE IF EXISTS ONLY public.warehouses DROP CONSTRAINT IF EXISTS uk6herdbg4x5wp6gkor8epv73oc;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS uk6dotkott2kjsp8vw4d0m25fb7;
ALTER TABLE IF EXISTS ONLY public.vendor_profiles DROP CONSTRAINT IF EXISTS uk54wrcif7ltdw3bocsbe3twow9;
ALTER TABLE IF EXISTS ONLY public.warehouses DROP CONSTRAINT IF EXISTS uk2qm0l82n5ivhyqwmgejxxefm1;
ALTER TABLE IF EXISTS ONLY public.products DROP CONSTRAINT IF EXISTS products_pkey;
ALTER TABLE IF EXISTS ONLY public.coupons DROP CONSTRAINT IF EXISTS coupons_pkey;
DROP TABLE IF EXISTS public.warehouses;
DROP TABLE IF EXISTS public.warehouse_stock;
DROP TABLE IF EXISTS public.vendor_profiles;
DROP TABLE IF EXISTS public.vendor_orders;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.products;
DROP TABLE IF EXISTS public.coupons;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: coupons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coupons (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(40) NOT NULL,
    discount_type character varying(20) NOT NULL,
    discount_value double precision NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    maximum_discount double precision,
    minimum_order_amount double precision,
    start_date timestamp(6) without time zone NOT NULL,
    usage_count integer NOT NULL,
    usage_limit integer
);


--
-- Name: coupons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.coupons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    approval_status character varying(255),
    category character varying(255),
    description character varying(255) NOT NULL,
    discount_percentage double precision DEFAULT 0 NOT NULL,
    image_url character varying(255),
    name character varying(255) NOT NULL,
    price double precision NOT NULL,
    returned_stock integer DEFAULT 0 NOT NULL,
    sold_quantity integer DEFAULT 0 NOT NULL,
    stock integer NOT NULL,
    vendor_id bigint NOT NULL
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    address character varying(255),
    commission_percentage double precision DEFAULT 10,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    password_reset_token character varying(255),
    password_reset_token_expiry timestamp(6) without time zone,
    phone character varying(255),
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vendor_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vendor_orders (
    id bigint NOT NULL,
    commission_amount double precision DEFAULT 0,
    commission_percentage double precision DEFAULT 0,
    customer_email character varying(255),
    customer_name character varying(255),
    customer_notification_read boolean NOT NULL,
    customer_phone character varying(255),
    customer_total_amount double precision DEFAULT 0,
    delivery_address character varying(255),
    delivery_method character varying(255),
    order_reference character varying(255),
    order_status character varying(255),
    payment_method character varying(255),
    placed_at timestamp(6) without time zone,
    previous_order_status character varying(255),
    product_id bigint,
    product_name character varying(255),
    quantity integer NOT NULL,
    refund_details character varying(255),
    refund_processed_at timestamp(6) without time zone,
    refund_reason character varying(255),
    refund_requested_at timestamp(6) without time zone,
    refund_status character varying(255),
    status character varying(255),
    total_amount double precision NOT NULL,
    unit_price double precision NOT NULL,
    warehouse_allocated_quantity integer NOT NULL,
    warehouse_name character varying(255),
    warehouse_status character varying(255),
    warehouse_updated_at timestamp(6) without time zone,
    vendor_id bigint NOT NULL
);


--
-- Name: vendor_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vendor_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vendor_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vendor_profiles (
    id bigint NOT NULL,
    address character varying(255),
    business_name character varying(255) NOT NULL,
    contact_number character varying(255),
    description character varying(1000),
    user_id bigint NOT NULL
);


--
-- Name: vendor_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vendor_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vendor_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouse_stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.warehouse_stock (
    id bigint NOT NULL,
    available_quantity integer NOT NULL,
    product_id bigint NOT NULL,
    warehouse_id bigint NOT NULL
);


--
-- Name: warehouse_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.warehouse_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouse_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: warehouses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.warehouses (
    id bigint NOT NULL,
    active boolean NOT NULL,
    address character varying(255),
    capacity integer NOT NULL,
    code character varying(255) NOT NULL,
    manager character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: warehouses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.warehouses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warehouses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: coupons; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.coupons (id, active, code, discount_type, discount_value, expiry_date, maximum_discount, minimum_order_amount, start_date, usage_count, usage_limit) FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.products (id, approval_status, category, description, discount_percentage, image_url, name, price, returned_stock, sold_quantity, stock, vendor_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, address, commission_percentage, email, password, password_reset_token, password_reset_token_expiry, phone, role, username) FROM stdin;
1	\N	10	admin@shopstack.com	$2a$10$MvYXiMLAnnlFP7/ituqoN.zCsm6uoaPb1swAp4imZZPM.FKAPZTWS	\N	\N	\N	ADMIN	Admin
2	\N	10	staff@shopstack.com	$2a$10$vQAbbJ6sobPX9lgjQnIiTuddCV9DC9LXrVZXj4u.gjMHMOc2ma.lG	\N	\N	\N	STAFF	Warehouse Staff
\.


--
-- Data for Name: vendor_orders; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.vendor_orders (id, commission_amount, commission_percentage, customer_email, customer_name, customer_notification_read, customer_phone, customer_total_amount, delivery_address, delivery_method, order_reference, order_status, payment_method, placed_at, previous_order_status, product_id, product_name, quantity, refund_details, refund_processed_at, refund_reason, refund_requested_at, refund_status, status, total_amount, unit_price, warehouse_allocated_quantity, warehouse_name, warehouse_status, warehouse_updated_at, vendor_id) FROM stdin;
\.


--
-- Data for Name: vendor_profiles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.vendor_profiles (id, address, business_name, contact_number, description, user_id) FROM stdin;
\.


--
-- Data for Name: warehouse_stock; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.warehouse_stock (id, available_quantity, product_id, warehouse_id) FROM stdin;
\.


--
-- Data for Name: warehouses; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.warehouses (id, active, address, capacity, code, manager, name) FROM stdin;
1	t	Peenya Industrial Area, Bengaluru	1200	BLR-01	Warehouse team	Bengaluru Central
2	t	Andheri East, Mumbai	1500	MUM-01	Warehouse team	Mumbai West
3	t	Bawana Industrial Area, Delhi	1000	DEL-01	Warehouse team	Delhi North
\.


--
-- Name: coupons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.coupons_id_seq', 1, false);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.products_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- Name: vendor_orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.vendor_orders_id_seq', 1, false);


--
-- Name: vendor_profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.vendor_profiles_id_seq', 1, false);


--
-- Name: warehouse_stock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.warehouse_stock_id_seq', 1, false);


--
-- Name: warehouses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.warehouses_id_seq', 3, true);


--
-- Name: coupons coupons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: warehouses uk2qm0l82n5ivhyqwmgejxxefm1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warehouses
    ADD CONSTRAINT uk2qm0l82n5ivhyqwmgejxxefm1 UNIQUE (name);


--
-- Name: vendor_profiles uk54wrcif7ltdw3bocsbe3twow9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendor_profiles
    ADD CONSTRAINT uk54wrcif7ltdw3bocsbe3twow9 UNIQUE (user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: warehouses uk6herdbg4x5wp6gkor8epv73oc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warehouses
    ADD CONSTRAINT uk6herdbg4x5wp6gkor8epv73oc UNIQUE (code);


--
-- Name: coupons ukeplt0kkm9yf2of2lnx6c1oy9b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT ukeplt0kkm9yf2of2lnx6c1oy9b UNIQUE (code);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vendor_orders vendor_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendor_orders
    ADD CONSTRAINT vendor_orders_pkey PRIMARY KEY (id);


--
-- Name: vendor_profiles vendor_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendor_profiles
    ADD CONSTRAINT vendor_profiles_pkey PRIMARY KEY (id);


--
-- Name: warehouse_stock warehouse_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warehouse_stock
    ADD CONSTRAINT warehouse_stock_pkey PRIMARY KEY (id);


--
-- Name: warehouses warehouses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.warehouses
    ADD CONSTRAINT warehouses_pkey PRIMARY KEY (id);


--
-- Name: vendor_profiles fkbdoc22aas6cny51wfhae92xit; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendor_profiles
    ADD CONSTRAINT fkbdoc22aas6cny51wfhae92xit FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: vendor_orders fkjlrsoj67iw6pmt6tc619p34ec; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vendor_orders
    ADD CONSTRAINT fkjlrsoj67iw6pmt6tc619p34ec FOREIGN KEY (vendor_id) REFERENCES public.users(id);


--
-- Name: products fklag4lc2yiaaehog28yd6lsoao; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fklag4lc2yiaaehog28yd6lsoao FOREIGN KEY (vendor_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict aZlBYzDhi08cj7wQs8ZRrf6ALRJ6ee5o7fLKtER4i2x3BV3xakTdQQ8mB1SkupB

