import { useEffect, useMemo, useState } from "react";
import { FaBoxOpen, FaExclamationTriangle, FaWarehouse } from "react-icons/fa";
import AdminSidebar from "./AdminSidebar";
import "./Admin.css";

const currency = (value) => `₹${Number(value || 0).toLocaleString("en-IN")}`;

export default function AdminWarehouse() {
  const [items, setItems] = useState([]); const [query, setQuery] = useState(""); const [vendor, setVendor] = useState("ALL"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const token = sessionStorage.getItem("token") || localStorage.getItem("token"); fetch("http://localhost:8080/api/admin/inventory", { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { if (!response.ok) throw new Error(await response.text() || "Unable to load warehouse inventory."); return response.json(); }).then(setItems).catch((requestError) => setError(requestError.message)).finally(() => setLoading(false)); }, []);
  const vendors = useMemo(() => [...new Map(items.map((item) => [item.vendorId, item.vendorName])).entries()], [items]);
  const visibleItems = useMemo(() => items.filter((item) => `${item.name} ${item.category || ""} ${item.vendorName}`.toLowerCase().includes(query.toLowerCase()) && (vendor === "ALL" || String(item.vendorId) === vendor)), [items, query, vendor]);
  const metrics = useMemo(() => ({ products: items.length, units: items.reduce((sum, item) => sum + Number(item.stock || 0), 0), low: items.filter((item) => Number(item.stock) <= 5).length, vendors: vendors.length }), [items, vendors]);
  return <div className="admin-dashboard-container"><AdminSidebar /><main className="admin-main admin-warehouse-main"><header className="warehouse-heading"><div><span className="orders-eyebrow">INVENTORY CONTROL</span><h1>Warehouse</h1><p>Monitor vendor products, available stock, and low inventory before orders are approved.</p></div><div className="warehouse-heading-icon"><FaWarehouse /></div></header><section className="warehouse-metrics"><div><span><FaBoxOpen /></span><strong>{metrics.products}</strong><small>Products listed</small></div><div><span><FaWarehouse /></span><strong>{metrics.units.toLocaleString("en-IN")}</strong><small>Units in stock</small></div><div><span><FaExclamationTriangle /></span><strong>{metrics.low}</strong><small>Low stock items</small></div><div><span>●</span><strong>{metrics.vendors}</strong><small>Active vendors</small></div></section><section className="warehouse-panel"><div className="warehouse-toolbar"><div><h2>Vendor inventory</h2><span>{visibleItems.length} products</span></div><div className="warehouse-controls"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products..." aria-label="Search inventory" /><select value={vendor} onChange={(event) => setVendor(event.target.value)} aria-label="Filter by vendor"><option value="ALL">All vendors</option>{vendors.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></div></div>{error && <div className="orders-alert">{error}</div>}{loading && <div className="orders-empty"><div className="orders-spinner" />Loading inventory...</div>}{!loading && !error && visibleItems.length === 0 && <div className="orders-empty"><strong>No inventory found</strong><span>Try another search or vendor.</span></div>}{!loading && !error && visibleItems.length > 0 && <div className="orders-table-wrap"><table className="admin-table orders-table warehouse-table"><thead><tr><th>Product</th><th>Vendor</th><th>Category</th><th>Price</th><th>Units available</th><th>Sold</th></tr></thead><tbody>{visibleItems.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small>SKU #{item.id}</small></td><td><strong>{item.vendorName}</strong><small>{item.vendorEmail}</small></td><td>{item.category || "Uncategorized"}</td><td><strong>{currency(item.price)}</strong></td><td><strong className={Number(item.stock) <= 5 ? "stock-low" : "stock-good"}>{Number(item.stock).toLocaleString("en-IN")}</strong></td><td>{Number(item.soldQuantity || 0).toLocaleString("en-IN")}</td></tr>)}</tbody></table></div>}</section></main></div>;
}
